<?php
$title=$this->translate('Sign Up');

$this->headMeta()->appendName('keywords','Sign up ,Create,Join,New Account');
$this->headMeta()->appendName('description','Create a new account');
$this->headTitle($this->escapeHtml('title'));
$form=$this->form;
$form->setAttribute('login',$this->url('login'));
$form->prepare();
?>

            <h3 class="mb-3 pt-2 text-md-center">
                <?=$this->escapeHtml($this->translate('Login'));?>
            </h3>

            <?=$this->form()->openTag($form);?>
            <!--email-->
            <div class="mb-3">
                <?=$this->formLabel($form->get('email'));?>
                <div class="form-group">
                    <?=$this->formEmail($form->get('email'));?>
                </div>
                <div class="text-danger">
                    <?=$this->formElementErrors($form->get('email'));?>
                </div>
            </div>
            
            <!-- password-->
            <div class="mb-3">
                <?=$this->formLabel($form->get('password'));?>
                <div class="form-group">
                    <?=$this->formPassword($form->get('password'));?>
                </div>
                <div class="text-danger">
                    <?=$this->formElementErrors($form->get('password'));?>
                </div>
            </div>
            <!--check box-->
            <div class="mb-3">
                <div class="custom-control custom-checkbox">
                    <?=$this->formCheckbox($form->get('recall'));?>
                    <?=$this->formLabel($form->get('recall'));?>
                </div>
            </div>
            <!--Button-->
            <div class="mb-3">
                <?=$this->formHidden($form->get('csrf'));?>
                <div class="text-danger">
                <?=$this->formElementErrors($form->get('csrf'));?>
                </div>
               <?=$this->formSubmit($form->get('account_login'));?>
               </div>
            <!-- close form-->
            <?=$this->form()->closeTag();?>
