<?php

$title = "Item";
$this->headtitle($title); 
$this->layout('layout/admin')?>

<h1 style='text-align: center;'>ITEM</h1>
<div class='top'>
    <p><a href=<?= $this->url('profile/item', ['action' => 'add']) ?> class='btn btn-primary'>Add Item</a></p>
</div>




<table class='table'>
    <thead>
        <tr>
            <th>Name</th>
            <th>Image</th>
            <th>Price</th>
            <th>Type</th>
            <th>Quantity</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($items as $item) : ?>
        <tr>
            <td style='padding-top: 30px'><?php echo $item['name'];?></td>
            <td>
                <img src="<?= $this->basePath('img/hinhminhhoa/') ?><?php echo $item['image'] ?>"" alt='image' width="150px">
            </td>
            <td style='padding-top: 30px'>$<?php echo ' '.$item['price'].' ';?></td>
            <td style='padding-top: 30px'><?php echo $item['catName'];?></td>
            <td style='padding-top: 30px'><?php echo $item['qty'];?></td>
            <td style='padding-top: 30px'><?php echo $item['status'];?></td>
            <td style='padding-top: 25px'>
                <a href=<?= $this->url('profile/item', ['action' => 'edit', 'id' => $item['item_id'] ])?> class='btn btn-info'><i class='fas fa-edit'></i></a>
                <a class='btn btn-danger delete_button' onclick="deleteItem(<?php echo $item['item_id']?>,'<?php echo $item['name']?>')" ><i class='fas fa-trash'></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<!-- Modal delete -->
<div class="modal fade" id="delete_modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    <?php
            $form->setAttribute('action', $this->url('profile/item', ['action' => 'delete']));
            $form->prepare();
    ?>
     <?=$this->form()->openTag($form);?>
        <div class="modal-header">
          <h5 class="modal-title" id="label_delete"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            Are you sure that you want to delete "<b id='name'></b>"
            <?=$this->formHidden($form->get('item_id2'));?>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type='submit' class="btn btn-danger">Yes</button>
        </div>
        <?=$this->form()->closeTag();?>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){

				
		   });
  /*function test(id){
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
        });
    $.ajax({
      url: '<?= $this->url('profile/item', ['action' => 'delete'])?>',
      type:'POST',
      //data:{'id':id},
      //dataType: 'json',
      success:function(data){
        alert(data[1])
      },
      error:function(){
        alert("fail");
      }
    });
  }*/
  function deleteItem(id,name){
    $('#name').html(name);
    $('#item_id2').val(id);
    //$('#del_form').attr('action', 'item/delete');
    $('#delete_modal').modal('show');
  }
</script>